language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x

script:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
  - overalls -project=github.com/ceshihao/multilines-struct-tag -covermode=count
  - goveralls -service=travis-ci -coverprofile=overalls.coverprofile
